on: [push]

jobs:
  show_contributors:
    runs-on: ubuntu-latest
    name: A job to get contributors
    steps:
      - name: GetContribs
        id: get-contribs
        uses: Keboo/GitHubHelper@master
        with:
          milestone: '5.0.0'
          repository: 'MaterialDesignInXamlToolkit'
          repository-owner: 'MaterialDesignInXAML'
          token: ${{ github.token }}
      - name: Get the output
        run: echo "${{ steps.get-contribs.outputs.contributors }}"